apiVersion: 1

datasources:
  - name: Mimir (Prometheus)
    type: prometheus
    uid: mimir
    url: http://mimir:9009/prometheus
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
    secureJsonData: {}

  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: 'traceID=(\w+)'
          name: TraceID
          url: '$${__value.raw}'
        - datasourceUid: mimir
          matcherRegex: 'service=(\w+)'
          name: Service
          url: 'var-service=$${__value.raw}'
    secureJsonData: {}

  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    editable: true
    jsonData:
      tracesToMetricsUI:
        enabled: true
        datasourceUid: mimir
      tracesToLogs:
        enabled: true
        datasourceUid: loki
    secureJsonData: {}

  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    url: http://alertmanager:9093
    access: proxy
    editable: true
    isDefault: false