multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /opt/homelab/data/monitoring/mimir

blocks_storage:
  backend: filesystem
  filesystem:
    dir: /opt/homelab/data/monitoring/mimir/blocks
  tsdb:
    dir: /opt/homelab/data/monitoring/mimir/tsdb

compactor:
  data_dir: /opt/homelab/data/monitoring/mimir/compactor

distributor:
  ring:
    kvstore:
      store: inmemory

ingester:
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1

ruler:
  rule_path: /opt/homelab/data/monitoring/mimir/rules
  alertmanager_url: http://monitoring_alertmanager:9093
