multitenancy_enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095

common:
  storage:
    backend: filesystem
    filesystem:
      dir: /opt/homelab/data/monitoring/mimir

blocks_storage:
  storage_backend: filesystem
  filesystem:
    dir: /opt/homelab/data/monitoring/mimir/blocks
  tsdb:
    dir: /opt/homelab/data/monitoring/mimir/tsdb

compactor:
  data_dir: /opt/homelab/data/monitoring/mimir/compactor

distributor:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

ingester:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
    replication_factor: 1

ruler:
  rule_path: /opt/homelab/data/monitoring/mimir/rules
  alertmanager_url: http://alertmanager:9093
  external_url: http://mimir:9009
  storage:
    type: local
    local:
      directory: /etc/mimir/rules
