services:
  prometheus:
    image: prom/prometheus
    volumes:
      - /opt/homelab/repo/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/homelab/data/prometheus:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  loki:
    image: grafana/loki:2.9.0
    volumes:
      - /opt/homelab/repo/monitoring/loki-config.yml:/etc/loki/config.yml
      - /opt/homelab/data/loki:/loki
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:2.9.0
    volumes:
      - /var/log:/var/log
      - /opt/homelab/repo/monitoring/promtail-config.yml:/etc/promtail/config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:2.3.0
    volumes:
      - /opt/homelab/repo/monitoring/tempo.yml:/etc/tempo.yml
      - /opt/homelab/data/tempo:/tmp/tempo
    command: -config.file=/etc/tempo.yml
    ports:
      - "3200:3200"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    volumes:
      - /opt/homelab/data/grafana_db:/var/lib/grafana
      - /opt/homelab/repo/monitoring/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3000:3000"
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    network_mode: host
    pid: host
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge