tunnel: 5220d09b-563e-4995-87d3-3ebd39d13110
credentials-file: /etc/cloudflared/tunnels/homelab-ghiorzi.json

ingress:
  - hostname: fotos.rafaelghiorzi.org
    service: http://192.168.0.185:2283

  - hostname: drive.rafaelghiorzi.org
    service: http://192.168.0.185:8080

  - hostname: nginx.rafaelghiorzi.org
    service: http://192.168.0.185:8000

  - hostname: flask.rafaelghiorzi.org
    service: http://192.168.0.185:5001

  - hostname: monitoring.rafaelghiorzi.org
    service: http://192.168.0.185:3000

  - service: http_status:404