tunnel: 3df0843e-4f2c-4ea1-8c6a-175aa904c6c8
credentials-file: /opt/homelab/secrets/tunnel-credentials.json

ingress:
  - hostname: fotos.rafaelghiorzi.org
    service: http://192.168.0.185:2283

  - hostname: drive.rafaelghiorzi.org
    service: http://192.168.0.185:8080

  - hostname: nginx.rafaelghiorzi.org
    service: http://192.168.0.185:8000

  - hostname: flask.rafaelghiorzi.org
    service: http://192.168.0.185:5001

  - hostname: monitoring.rafaelghiorzi.org
    service: http://192.168.0.185:3000

  - service: http_status:404