name: Homelab Sync
on:
  push:
    branches: [ main ]

jobs:
  setup-and-sync:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files to /opt/homelab/repo
        run: |
          mkdir -p /opt/homelab/repo
          rsync -rtv --delete ./ /opt/homelab/repo/

  deploy:
    needs: setup-and-sync
    steps:
      - name: Deploy Nginx
        run: |
          echo "Deploying Nginx"
          docker compose -f /opt/homelab/repo/apps/nginx/docker-compose.yml up -d